server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://150.158.167.162:3306/ice?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF8
    username: root
    password: lmzs1111
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    # 设置上传文件以及请求大小 默认为1MB和10MB
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB


mybatis-plus:
  #配置了myabtis plus的mapper的xml文件的扫描路径
  #   mapper-locations: classpath*:/mapper/**Mapper.xml
  #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID


